"""Generate overview tables from canonical CSV outputs.

Stdlib-only implementation to avoid environment-specific dependencies.
Run from project root:
    python3 papers/tables/generate_tables_ch4_overview.py
"""

from __future__ import annotations

import csv
import math
import shutil
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
OUT = Path(__file__).resolve().parent / "ch4"
OUT.mkdir(parents=True, exist_ok=True)

FILES = {
    "T1": ROOT / "results/test1_ontological_innovation/test1_results.csv",
    "T2": ROOT / "results/test2_epistemic_agency/test2_results.csv",
    "T3": ROOT / "results/test3_theory_generation/test3_results.csv",
    "T4": ROOT / "results/test4_category_recognition/test4_results.csv",
}

TEST_NAMES = {
    "T1": "Test 1: Ontological Innovation",
    "T2": "Test 2: Epistemic Agency",
    "T3": "Test 3: Theory Generation",
    "T4": "Test 4: Category Recognition",
}

ALIASES = {
    "perplexity-sonar": "perplexity-sonar-pro",
    "perplexity/sonar": "perplexity-sonar-pro",
    "perplexity/sonar-pro": "perplexity-sonar-pro",
    "perplexity-sonar-pro-pro": "perplexity-sonar-pro",
}

HEADER = "% AUTO-GENERATED by papers/tables/generate_tables_ch4_overview.py - do not edit by hand.\n"


def load_rows(path: Path) -> list[dict[str, str]]:
    with path.open(newline="", encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


def find_col(rows: list[dict[str, str]], candidates: list[str]) -> str | None:
    if not rows:
        return None
    lowered = {key.lower(): key for key in rows[0].keys()}
    for candidate in candidates:
        if candidate.lower() in lowered:
            return lowered[candidate.lower()]
    return None


def parse_float(value: str | None) -> float | None:
    try:
        if value is None or str(value).strip() == "":
            return None
        return float(value)
    except Exception:
        return None


def parse_bool01(value: str | None) -> float | None:
    if value is None:
        return None
    mapping = {
        "true": 1.0,
        "t": 1.0,
        "yes": 1.0,
        "y": 1.0,
        "1": 1.0,
        "false": 0.0,
        "f": 0.0,
        "no": 0.0,
        "n": 0.0,
        "0": 0.0,
        "maybe": 1.0,
    }
    return mapping.get(str(value).strip().lower())


def mean(values: list[float | None]) -> float:
    arr = [value for value in values if value is not None]
    return sum(arr) / len(arr) if arr else float("nan")


def std(values: list[float | None]) -> float:
    arr = [value for value in values if value is not None]
    if len(arr) < 2:
        return float("nan")
    mu = sum(arr) / len(arr)
    return (sum((value - mu) ** 2 for value in arr) / (len(arr) - 1)) ** 0.5


def ci_norm(values: list[float | None]) -> tuple[float, float]:
    arr = [value for value in values if value is not None]
    if not arr:
        return float("nan"), float("nan")
    p = sum(arr) / len(arr)
    se = math.sqrt(max(p * (1 - p) / len(arr), 0.0))
    return max(0.0, p - 1.96 * se), min(1.0, p + 1.96 * se)


def esc(text: str) -> str:
    return str(text).replace("_", "\\_")


def format_metric_label(text: str) -> str:
    raw = str(text).strip()
    if not raw:
        return ""

    mapping = {
        "continuous_novelty_score >= 0.5": "continuous novelty score $\\geq 0.5$",
        "Continuous_Literature_Novelty >= 0.5": "continuous literature novelty $\\geq 0.5$",
        "continuous_literature_novelty >= 0.5": "continuous literature novelty $\\geq 0.5$",
        "literature_novelty_score >= 0.5": "literature novelty score $\\geq 0.5$",
        "global_novelty_score >= 0.5": "global novelty score $\\geq 0.5$",
        "novelty_score >= 0.5": "novelty score $\\geq 0.5$",
        "novelty_ratio >= 0.5": "novelty ratio $\\geq 0.5$",
        "Transcends_Framework (binary)": "framework-transcendence flag",
        "transcends_framework (binary)": "framework-transcendence flag",
        "Is_Transcendent (binary)": "framework-transcendence flag",
        "is_transcendent (binary)": "framework-transcendence flag",
        "Is_Novel (binary)": "binary novelty flag",
        "is_novel (binary)": "binary novelty flag",
        "Ontologically_Novel (binary)": "ontological novelty flag",
        "ontologically_novel (binary)": "ontological novelty flag",
        "Novel_Non_Functionalist (binary)": "non-functionalist novelty flag",
        "novel_non_functionalist (binary)": "non-functionalist novelty flag",
        "Original (binary)": "originality flag",
        "original (binary)": "originality flag",
        "total_score / 15 >= 0.5": "normalized total score $\\geq 0.5$",
        "alternative_score >= 4.0": "alternative score $\\geq 4.0$",
        "is_traceable": "traceability flag",
        "Training_Derived": "training-derived flag",
        "training_derived": "training-derived flag",
        "Likely_Derivative": "likely-derivative flag",
        "likely_derivative": "likely-derivative flag",
        "lit_matches > 0": "literature matches $> 0$",
        "max_similarity >= 0.8": "maximum similarity $\\geq 0.8$",
        "similarity >= 0.8": "similarity $\\geq 0.8$",
        "similarity_max_to_known >= 0.55": "max similarity to known theories $\\geq 0.55$",
        "max_similarity >= 0.55": "maximum similarity $\\geq 0.55$",
        "similarity >= 0.55": "similarity $\\geq 0.55$",
    }
    if raw in mapping:
        return mapping[raw]

    return esc(raw).replace(">=", "$\\geq$")


def write_table(filename: str, body: str) -> None:
    (OUT / filename).write_text(HEADER + body + "\n", encoding="utf-8")


ROW_END = r"\\"


def build() -> None:
    summary: list[dict[str, object]] = []
    model_test_means: dict[tuple[str, str], float] = {}

    for code, path in FILES.items():
        rows = load_rows(path)
        model_col = find_col(rows, ["model"])
        if model_col:
            for row in rows:
                model = str(row.get(model_col, "")).strip()
                row[model_col] = ALIASES.get(model, model)

        novelty: list[float | None] | None = None
        novelty_label = ""

        col = find_col(rows, ["continuous_novelty_score"])
        if col:
            novelty = [1.0 if (parse_float(r.get(col)) is not None and max(0.0, min(1.0, parse_float(r.get(col)))) >= 0.5) else 0.0 for r in rows]
            novelty_label = "continuous_novelty_score >= 0.5"

        if novelty is None and code == "T3":
            col = find_col(rows, ["continuous_literature_novelty", "literature_novelty_score", "global_novelty_score", "novelty_score"])
            if col:
                novelty = [1.0 if (parse_float(r.get(col)) is not None and max(0.0, min(1.0, parse_float(r.get(col)))) >= 0.5) else 0.0 for r in rows]
                novelty_label = f"{col} >= 0.5"

        if novelty is None:
            col = find_col(rows, ["novelty_score"])
            if col:
                novelty = [1.0 if (parse_float(r.get(col)) is not None and max(0.0, min(1.0, parse_float(r.get(col)))) >= 0.5) else 0.0 for r in rows]
                novelty_label = f"{col} >= 0.5"

        if novelty is None:
            col = find_col(rows, ["novelty_ratio"])
            if col:
                novelty = [1.0 if (parse_float(r.get(col)) is not None and max(0.0, min(1.0, parse_float(r.get(col)))) >= 0.5) else 0.0 for r in rows]
                novelty_label = "novelty_ratio >= 0.5"

        if novelty is None:
            col = find_col(rows, ["transcends_framework", "is_transcendent", "is_novel", "ontologically_novel", "novel_non_functionalist", "original"])
            if col:
                novelty = [(parse_bool01(r.get(col)) if parse_bool01(r.get(col)) is not None else 0.0) for r in rows]
                novelty_label = f"{col} (binary)"

        if novelty is None and code == "T4":
            col = find_col(rows, ["total_score"])
            if col:
                novelty = [1.0 if (parse_float(r.get(col)) is not None and max(0.0, min(1.0, parse_float(r.get(col)) / 15.0)) >= 0.5) else 0.0 for r in rows]
                novelty_label = "total_score / 15 >= 0.5"

        if novelty is None:
            col = find_col(rows, ["alternative_score"])
            if col:
                novelty = [1.0 if (parse_float(r.get(col)) is not None and parse_float(r.get(col)) >= 4.0) else 0.0 for r in rows]
                novelty_label = "alternative_score >= 4.0"

        novel_kind: list[float | None] | None = None
        novel_kind_label = ""
        for candidate in ["continuous_novelty_score", "continuous_literature_novelty", "literature_novelty_score", "global_novelty_score", "novelty_score", "novelty_ratio"]:
            col = find_col(rows, [candidate])
            if col:
                novel_kind = [max(0.0, min(1.0, parse_float(r.get(col)))) if parse_float(r.get(col)) is not None else None for r in rows]
                novel_kind_label = f"{col} mean"
                break

        if novel_kind is None:
            col = find_col(rows, ["total_score"])
            if col:
                novel_kind = [max(0.0, min(1.0, parse_float(r.get(col)) / 15.0)) if parse_float(r.get(col)) is not None else None for r in rows]
                novel_kind_label = "total_score / 15 mean"

        if novel_kind is None:
            col = find_col(rows, ["alternative_score"])
            if col:
                novel_kind = [max(0.0, min(1.0, ((parse_float(r.get(col)) - 1.0) / 4.0))) if parse_float(r.get(col)) is not None else None for r in rows]
                novel_kind_label = "alternative_score normalized mean"

        if novel_kind is None:
            novel_kind = novelty
            novel_kind_label = novelty_label

        trace: list[float | None] | None = None
        trace_label = ""

        col = find_col(rows, ["is_traceable"])
        if col:
            trace = [(parse_bool01(r.get(col)) if parse_bool01(r.get(col)) is not None else 0.0) for r in rows]
            trace_label = "is_traceable"

        if trace is None:
            col = find_col(rows, ["lit_matches"])
            if col:
                trace = [1.0 if ((parse_float(r.get(col)) or 0.0) > 0.0) else 0.0 for r in rows]
                trace_label = "lit_matches > 0"

        if trace is None:
            col = find_col(rows, ["training_derived", "likely_derivative"])
            if col:
                trace = [(parse_bool01(r.get(col)) if parse_bool01(r.get(col)) is not None else 0.0) for r in rows]
                trace_label = col

        if trace is None:
            col = find_col(rows, ["max_similarity", "similarity", "similarity_max_to_known"])
            if col:
                threshold = 0.55 if code == "T3" else 0.8
                trace = [1.0 if (parse_float(r.get(col)) is not None and parse_float(r.get(col)) >= threshold) else 0.0 for r in rows]
                trace_label = f"{col} >= {threshold:g}"

        col = find_col(rows, ["max_similarity", "similarity", "similarity_max_to_known"])
        sim = [parse_float(r.get(col)) if col else None for r in rows]

        models = set(r.get(model_col) for r in rows) if model_col else set()
        summary.append(
            {
                "test_code": code,
                "test_name": TEST_NAMES[code],
                "total_samples": len(rows),
                "n_models": len(models),
                "prop_novel": mean(novelty),
                "prop_novel_ci": ci_norm(novelty),
                "novelty_metric": novelty_label,
                "prop_traceable": mean(trace),
                "prop_traceable_ci": ci_norm(trace),
                "trace_metric": trace_label,
                "prop_novel_kind": mean(novel_kind),
                "prop_novel_kind_ci": ci_norm([value for value in novel_kind if value is not None]),
                "novel_kind_label": novel_kind_label,
                "mean_similarity": mean(sim),
                "std_similarity": std(sim),
            }
        )

        metric: list[float | None] | None = None
        col = find_col(rows, ["continuous_novelty_score"])
        if code == "T1" and col:
            metric = [max(0.0, min(1.0, parse_float(r.get(col)))) if parse_float(r.get(col)) is not None else None for r in rows]

        if metric is None and code == "T2":
            col = find_col(rows, ["novelty_score", "novelty_ratio"])
            if col:
                metric = [max(0.0, min(1.0, parse_float(r.get(col)))) if parse_float(r.get(col)) is not None else None for r in rows]
            else:
                col = find_col(rows, ["transcends_framework", "is_transcendent"])
                if col:
                    metric = [parse_bool01(r.get(col)) if parse_bool01(r.get(col)) is not None else 0.0 for r in rows]

        if metric is None and code == "T3":
            col = find_col(rows, ["continuous_literature_novelty", "literature_novelty_score", "global_novelty_score", "novelty_score"])
            if col:
                metric = [max(0.0, min(1.0, parse_float(r.get(col)))) if parse_float(r.get(col)) is not None else None for r in rows]

        if metric is None and code == "T4":
            col = find_col(rows, ["total_score"])
            if col:
                metric = [max(0.0, min(1.0, parse_float(r.get(col)) / 15.0)) if parse_float(r.get(col)) is not None else None for r in rows]

        if metric is None:
            col = find_col(rows, ["is_novel", "ontologically_novel", "novel_non_functionalist", "original"])
            if col:
                metric = [parse_bool01(r.get(col)) if parse_bool01(r.get(col)) is not None else 0.0 for r in rows]

        if metric is None:
            col = find_col(rows, ["novelty_score", "novelty_ratio"])
            if col:
                metric = [max(0.0, min(1.0, parse_float(r.get(col)))) if parse_float(r.get(col)) is not None else None for r in rows]

        if metric is None:
            col = find_col(rows, ["alternative_score"])
            if col:
                metric = [max(0.0, min(1.0, ((parse_float(r.get(col)) - 1.0) / 4.0))) if parse_float(r.get(col)) is not None else None for r in rows]

        by_model: dict[str, list[float]] = {}
        if metric is not None:
            for row, value in zip(rows, metric):
                model = row.get(model_col)
                if model is None or value is None:
                    continue
                by_model.setdefault(model, []).append(value)

        for model, values in by_model.items():
            model_test_means[(model, code)] = mean(values)

    summary.sort(key=lambda row: row["test_code"])
    models_sorted = sorted({model for model, _ in model_test_means.keys()})

    raw = {model: {test_code: model_test_means.get((model, test_code), float("nan")) for test_code in ["T1", "T2", "T3", "T4"]} for model in models_sorted}
    z = {model: {} for model in models_sorted}

    for test_code in ["T1", "T2", "T3", "T4"]:
        values = [raw[model][test_code] for model in models_sorted if not math.isnan(raw[model][test_code])]
        if len(values) >= 2:
            mu = sum(values) / len(values)
            sigma = (sum((value - mu) ** 2 for value in values) / (len(values) - 1)) ** 0.5
            for model in models_sorted:
                value = raw[model][test_code]
                z[model][test_code] = 0.0 if math.isnan(value) or sigma == 0 else (value - mu) / sigma
        else:
            for model in models_sorted:
                z[model][test_code] = 0.0

    ranking: list[tuple[str, float]] = []
    for model in models_sorted:
        values = [raw[model][test_code] for test_code in ["T1", "T2", "T3", "T4"] if not math.isnan(raw[model][test_code])]
        ranking.append((model, sum(values) / len(values) if values else float("nan")))
    ranking.sort(key=lambda item: item[1], reverse=True)

    lines = [
        "\\begin{table}[htbp]",
        "  \\centering",
        "  \\begin{footnotesize}",
        "  \\caption{Aggregate statistics across all empirical tests.}",
        "  \\label{tab:overview_aggregate_stats}",
        "  \\begin{threeparttable}",
        "  \\begin{tabularx}{\\textwidth}{@{}L{0.80} S[table-format=4.0] S[table-format=1.0] L{1.20}@{}}",
        "    \\toprule",
        "    \\textbf{Test} & {\\textbf{$N$}} & {\\textbf{Models}} & \\textbf{Primary novelty-oriented metric} " + ROW_END,
        "    \\midrule",
    ]
    for row in summary:
        short = row["test_name"].split(":", 1)[1].strip()
        lines.append(f"    {row['test_code']} ({short}) & {row['total_samples']} & {row['n_models']} & {format_metric_label(row['novelty_metric'])} " + ROW_END)
    lines.extend([
        "    \\midrule",
        f"    \\textbf{{Total}} & {sum(row['total_samples'] for row in summary)} & {max(row['n_models'] for row in summary)} & test-specific operationalization " + ROW_END,
        "    \\bottomrule",
        "  \\end{tabularx}",
        "  \\begin{tablenotes}",
        "    \\item Metrics follow each test's validated schema; cross-test comparability is handled using standardized views (Table~\\ref{tab:overview_cross_model_z}).",
        "  \\end{tablenotes}",
        "  \\end{threeparttable}",
        "  \\end{footnotesize}",
        "\\end{table}",
    ])
    write_table("overview_aggregate_stats.tex", "\n".join(lines))

    lines = [
        "\\begin{table}[htbp]",
        "  \\centering",
        "  \\begin{footnotesize}",
        "  \\caption{Novelty and traceability summary by test.}",
        "  \\label{tab:overview_novelty_traceability}",
        "  \\begin{tabularx}{\\textwidth}{@{}L{1.00} S[table-format=2.2] S[table-format=1.3] S[table-format=1.3] S[table-format=3.2] S[table-format=1.3] S[table-format=1.3]@{}}",
        "    \\toprule",
        "    \\textbf{Test} & {\\textbf{Novel (\\%)}} & {\\textbf{CI Low}} & {\\textbf{CI High}} & {\\textbf{Traceable (\\%)}} & {\\textbf{CI Low}} & {\\textbf{CI High}} " + ROW_END,
        "    \\midrule",
    ]
    for row in summary:
        novel_lo, novel_hi = row["prop_novel_ci"]
        trace_lo, trace_hi = row["prop_traceable_ci"]
        lines.append(f"    {row['test_code']} & {100 * row['prop_novel']:.2f} & {novel_lo:.3f} & {novel_hi:.3f} & {100 * row['prop_traceable']:.2f} & {trace_lo:.3f} & {trace_hi:.3f} " + ROW_END)
    lines.extend(["    \\bottomrule", "  \\end{tabularx}", "  \\end{footnotesize}", "\\end{table}"])
    write_table("overview_novelty_traceability.tex", "\n".join(lines))

    lines = [
        "\\begin{table}[htbp]",
        "  \\centering",
        "  \\begin{footnotesize}",
        "  \\caption{Extended overview summary with novelty-kind and similarity diagnostics.}",
        "  \\label{tab:overview_extended_summary}",
        "  \\begin{threeparttable}",
        "  \\begin{tabularx}{\\textwidth}{@{}L{0.70} S[table-format=2.2] S[table-format=2.2] S[table-format=1.3] S[table-format=1.3] L{1.30}@{}}",
        "    \\toprule",
        "    \\textbf{Test} & {\\textbf{Novel (\\%)}} & {\\textbf{Novel-kind (\\%)}} & {\\textbf{Mean Sim.}} & {\\textbf{SD Sim.}} & \\textbf{Traceability metric} " + ROW_END,
        "    \\midrule",
    ]
    for row in summary:
        lines.append(f"    {row['test_code']} & {100 * row['prop_novel']:.2f} & {100 * row['prop_novel_kind']:.2f} & {row['mean_similarity']:.3f} & {row['std_similarity']:.3f} & {format_metric_label(row['trace_metric'])} " + ROW_END)
    lines.extend([
        "    \\bottomrule",
        "  \\end{tabularx}",
        "  \\begin{tablenotes}",
        "    \\item Novel-kind retains each test's secondary signal (continuous where available; binary proxy otherwise).",
        "  \\end{tablenotes}",
        "  \\end{threeparttable}",
        "  \\end{footnotesize}",
        "\\end{table}",
    ])
    write_table("overview_extended_summary.tex", "\n".join(lines))

    lines = [
        "\\begin{table}[htbp]",
        "  \\centering",
        "  \\begin{footnotesize}",
        "  \\caption{Cross-model comparison matrix: raw mean novelty-oriented score by test.}",
        "  \\label{tab:overview_cross_model_raw}",
        "  \\begin{threeparttable}",
        "  \\begin{tabularx}{\\textwidth}{@{}L{1.00} S[table-format=1.3] S[table-format=1.3] S[table-format=1.3] S[table-format=1.3]@{}}",
        "    \\toprule",
        "    \\textbf{Model} & {\\textbf{T1}} & {\\textbf{T2}} & {\\textbf{T3}} & {\\textbf{T4}} " + ROW_END,
        "    \\midrule",
    ]
    for model in models_sorted:
        lines.append(f"    {esc(model)} & {raw[model]['T1']:.3f} & {raw[model]['T2']:.3f} & {raw[model]['T3']:.3f} & {raw[model]['T4']:.3f} " + ROW_END)
    lines.extend([
        "    \\bottomrule",
        "  \\end{tabularx}",
        "  \\begin{tablenotes}",
        "    \\item Raw values are not strictly cross-test comparable because each column uses a test-specific metric definition.",
        "  \\end{tablenotes}",
        "  \\end{threeparttable}",
        "  \\end{footnotesize}",
        "\\end{table}",
    ])
    write_table("overview_cross_model_raw.tex", "\n".join(lines))

    lines = [
        "\\begin{table}[htbp]",
        "  \\centering",
        "  \\begin{footnotesize}",
        "  \\caption{Cross-model comparison matrix: within-test standardized z-scores.}",
        "  \\label{tab:overview_cross_model_z}",
        "  \\begin{threeparttable}",
        "  \\begin{tabularx}{\\textwidth}{@{}L{1.00} S[table-format=1.3] S[table-format=1.3] S[table-format=1.3] S[table-format=1.3]@{}}",
        "    \\toprule",
        "    \\textbf{Model} & {\\textbf{T1}} & {\\textbf{T2}} & {\\textbf{T3}} & {\\textbf{T4}} " + ROW_END,
        "    \\midrule",
    ]
    for model in models_sorted:
        lines.append(f"    {esc(model)} & {z[model]['T1']:.3f} & {z[model]['T2']:.3f} & {z[model]['T3']:.3f} & {z[model]['T4']:.3f} " + ROW_END)
    lines.extend([
        "    \\bottomrule",
        "  \\end{tabularx}",
        "  \\begin{tablenotes}",
        "    \\item Z-scores are computed independently within each test across models, enabling across-column comparison.",
        "  \\end{tablenotes}",
        "  \\end{threeparttable}",
        "  \\end{footnotesize}",
        "\\end{table}",
    ])
    write_table("overview_cross_model_z.tex", "\n".join(lines))

    lines = [
        "\\begin{table}[htbp]",
        "  \\centering",
        "  \\begin{footnotesize}",
        "  \\caption{Model ranking by mean novelty-oriented score across tests (T1--T4).}",
        "  \\label{tab:overview_model_ranking}",
        "  \\begin{tabularx}{\\textwidth}{@{}S[table-format=1.0] L{1.00} S[table-format=1.3]@{}}",
        "    \\toprule",
        "    \\textbf{Rank} & \\textbf{Model} & {\\textbf{Mean Across Tests}} " + ROW_END,
        "    \\midrule",
    ]
    for idx, (model, score) in enumerate(ranking, start=1):
        lines.append(f"    {idx} & {esc(model)} & {score:.3f} " + ROW_END)
    lines.extend(["    \\bottomrule", "  \\end{tabularx}", "  \\end{footnotesize}", "\\end{table}"])
    write_table("overview_model_ranking.tex", "\n".join(lines))

    media = ROOT / "papers/media/chapter4"
    media.mkdir(parents=True, exist_ok=True)
    shutil.copy2(ROOT / "results/overview/cross-test_model-comparison.png", media / "cross-test_model-comparison.png")
    if (ROOT / "results/overview/findings_dashboard_A.png").exists():
        shutil.copy2(ROOT / "results/overview/findings_dashboard_A.png", media / "findings_dashboard_A.png")
    if (ROOT / "results/overview/findings_dashboard_B.png").exists():
        shutil.copy2(ROOT / "results/overview/findings_dashboard_B.png", media / "findings_dashboard_B.png")
    if (ROOT / "results/overview/findings_dashboard.png").exists():
        shutil.copy2(ROOT / "results/overview/findings_dashboard.png", media / "findings_dashboard.png")

    print("Wrote:")
    for path in sorted(OUT.glob("overview_*.tex")):
        print(" -", path.relative_to(ROOT))
    print("Copied figures to papers/media/chapter4/")


if __name__ == "__main__":
    build()